name: restaurant_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.2
  flutter_switch: ^0.3.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  loading_animation_widget: ^1.2.0+2
  lottie: ^1.4.2
  readmore: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
